version: 2
updates:
- package-ecosystem: cargo
  directory: /
  schedule:
    interval: monthly
  commit-message:
    prefix: 'chore(deps):'
  labels:
  - dependencies
  - rust
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
  commit-message:
    prefix: 'ci(dependabot):'
  labels:
  - ci
  - dependencies
