name: Code Coverage

on: [push, pull_request]
jobs:
  test:
    name: Coverage
    runs-on: ubuntu-latest
    services:
      languagetool:
        image: erikvl87/languagetool:latest
        ports:
        - 8010:8010
        env:
          langtool_maxTextLength: 1500
          Java_Xmx: 2g
    env:
      LANGUAGETOOL_HOSTNAME: http://localhost
      LANGUAGETOOL_PORT: 8010
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install nightly toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2

    - name: Install cargo-tarpaulin
      run: cargo +nightly install cargo-tarpaulin --locked

    - name: Ping server
      run: cargo run -- -vv ping

    - name: Generate code coverage
      run: |
        cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 120 --out Xml

    - name: Upload to codecov.io
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
